
spring:
  application:
      name: single-server
  # 单机redis 配置
  redis:
#    host: 192.168.99.100
    host: 172.16.5.12
    port: 6379
    database: 12
    password: jkct-redis-123456
#  profiles:
#    active: dev




server:
  port: 10002
  servlet:
    context-path: /
#  address: localhost




