
spring:
  application:
      name: single-server
  # 单机redis 配置
  redis:
    host: 192.168.99.100
    port: 6379
    database: 1
#  profiles:
#    active: dev




server:
  port: 10000
  servlet:
    context-path: /
#  address: localhost




