
spring:
  application:
      name: redis-cluster
  # 单机redis 配置
  redis:
    host: 172.16.4.79
    port: 8001
    database: 0
    password: hzsun
#    cluster:
#      nodes: 172.16.4.79:8001

#  profiles:
#    active: dev




server:
  port: 10000
#  servlet:
#    context-path: /
#  address: localhost




